// Run with: sh ./T4/Generators.sh

using System;
using System.Collections.Generic;
using System.Linq;

public static class Generator {
  public static void WriteVariant(this System.IO.StreamWriter o, string header, string footer, string qualifier, string name, Dictionary<string, string> variant) {
    o.WriteLine("// This file was generated by Generator.cs");
    o.WriteLine("");

    o.WriteLine($"{header}");
    o.WriteLine("");

    o.WriteLine($"  /* To match against an instance of {name}, write:");
    o.WriteLine($"     x.Match(");
    o.WriteLine(String.Join(",\n", variant.Select(@case => 
                $"       {@case.Key}: {@case.Value == null ? "()" : "value"} => throw new NotImplementedYetException(),")));
    o.WriteLine($"     )");
    o.WriteLine($"  */");

    o.WriteLine($"  public abstract class {name} {{");
    o.WriteLine($"    public abstract T Match_<T>(Visitor<T> c);");
    foreach (var @case in variant) {
      var C = @case.Key;
      var Ty = @case.Value;
      o.WriteLine($"    public static {name} {C}{Ty == null ? $" = new {C}()" : $"({Ty} value) => new {C}(value)"};");
    }

    foreach (var @case in variant) {
      var C = @case.Key;
      var Ty = @case.Value;
      o.WriteLine($"    public virtual Immutable.Option<{C}> As{C}() => Immutable.Option.None<{C}>();");
    }

    o.WriteLine($"    private string GetTag() {{");
    o.WriteLine($"      return this.Match(");
    o.WriteLine(String.Join(",\n", variant.Select(@case =>
                $"        {@case.Key}: {@case.Value == null ? "()" : "value"} => \"{@case.Key}\"")));
    o.WriteLine($"      );");
    o.WriteLine($"    }}");

/*
    public abstract override bool Equals(object other) {
      if (object.ReferenceEquals(other, null) || !this.GetType().Equals(other.GetType())) {
        return false;
      } else {
        var cast = (S)other;
        return    String.Equal(this.GetTag(), other.GetTag)
               && 
    }
*/

    o.WriteLine($"  }}");
    o.WriteLine("");

    foreach (var @case in variant) {
      var C = @case.Key;
      var Ty = @case.Value;

      o.WriteLine(
        $"  public partial class Visitor<T> {{"
        + $" public Func<{Ty == null ? "" : $"{Ty}, "}T> {C} {{ get; set; }} "
        + @"}");
      o.WriteLine("");

      o.WriteLine($"  public sealed class {C} : {name} {{");
      if (Ty != null) {
        o.WriteLine($"    public readonly {Ty} value;");
      }
      o.WriteLine($"    public {C}({Ty == null ? "" : $"{Ty} value"}) {{ {Ty == null ? "" : $"this.value = value; "}}}");
      o.WriteLine($"    public override T Match_<T>(Visitor<T> c) => c.{C}({Ty == null ? "" : "value"});");
      o.WriteLine($"    public override Immutable.Option<{C}> As{C}() => Immutable.Option.Some<{C}>(this);");
      o.WriteLine($"    public override bool Equals(object other) {{");
      if (Ty == null) {
        o.WriteLine($"        return (other is {C});");
      } else {
        o.WriteLine($"      var cast = other as {C};");
        o.WriteLine($"      if (Object.ReferenceEquals(cast, null)) {{");
        o.WriteLine($"        return false;");
        o.WriteLine($"      }} else {{");
        o.WriteLine($"        return Equality.Field<{C}, {Ty}>(this, cast, x => x.value, (x, y) => ((Object)x).Equals(y));");
        o.WriteLine($"      }}");
      }
      o.WriteLine($"    }}");
      o.WriteLine($"    public override int GetHashCode() {{");
      if (Ty == null) {
        o.WriteLine($"        return \"C\".GetHashCode();");
      } else {
        o.WriteLine($"        return HashCode.Combine(\"{C}\", this.value);");
      }
      o.WriteLine($"    }}");
      o.WriteLine("");
      o.WriteLine($"    public override string ToString() => \"{C}\";");
      o.WriteLine($"  }}");
      o.WriteLine("");
    }

    o.WriteLine($"}}");

    o.WriteLine($"public static class {name}ExtensionMethods {{");
    o.WriteLine($"  public static T Match<T>(");
    o.WriteLine($"      this {qualifier}{name} e,");
    o.WriteLine(String.Join(",\n", variant.Select(c =>
                $"      Func<{c.Value == null ? "" : $"{c.Value}, "}T> {c.Key}")));
    o.WriteLine($"    ) {{");
    o.WriteLine($"    return e.Match_(new {qualifier}Visitor<T> {{");
    o.WriteLine(String.Join(",\n", variant.Select(c =>
                $"      {c.Key} = {c.Key}")));
    o.WriteLine($"    }});");
    o.WriteLine($"  }}");
    o.WriteLine($"{footer}");
  }

  public static void Generate(string outputFile, string header, string footer, string qualifier, string name, Dictionary<string, string> variant) {
    using (var o = new System.IO.StreamWriter(outputFile)) {
      o.WriteLine("using System;");
      o.WriteLine("");
      o.WriteVariant(header, footer, qualifier, name, variant);
    }
  }
}